### ISSUE TITLE
Question | Make Entity Invisible

### ISSUE THREAD

**Issue by micartey** [Tofaa2/EntityLib#1]
Hello there 👋🏼 

Is there a way to make an entity invisible (no effect) by `entityId` ?
That means an entity that hasn't been created by the library but is spawned and on the server.

This was possible by using DataWatchers and setting index `0` to `0x20 & 1` (invisible)
([See section Entity Metadata > Entity](https://wiki.vg/Entity_metadata))

**Comment by Tofaa2** [comment]
Hey, using EntityLib you can construct your own EntityMeta using EntityLib.createMeta(int entityId, EntityType entityType), make sure the entityId is your entities ID, and the types match. Once you do that you can set the meta as invisible and get the packet by calling EntityMeta#createPacket(). Issues should be for issues/suggestions, if you have anything else to ask feel free to either dm me (tofaa on discord) or join the Discord server from the readme of EntityLib
