### ISSUE TITLE
[Feature] Save all entity values

### ISSUE THREAD

**Issue by mani1232** [Tofaa2/EntityLib#14]

**Comment by Tofaa2** [comment]
https://github.com/Tofaa2/EntityLib/blob/master/platforms/spigot/src/main/java/me/tofaa/entitylib/spigot/SpigotEntityLibAPI.java#L45
It's already a thing, though not ideal or converts every values

**Comment by mani1232** [comment]
@Tofaa2 How get head rotation 
![image](https://github.com/user-attachments/assets/b77f915c-b43f-4790-ad47-b7c088ff64ad)
im need it, why you dont save it
![image](https://github.com/user-attachments/assets/bbdf203a-8dd7-4658-acc5-0bf1d9069a77)

**Comment by mani1232** [comment]
![image](https://github.com/user-attachments/assets/af460258-aa11-47c6-915f-ace6614c6715)
creating entity

**Comment by mani1232** [comment]
and why im need pass location here 
![image](https://github.com/user-attachments/assets/6240bed7-e492-48d4-ad25-60f54f966009)
if im set it here
![image](https://github.com/user-attachments/assets/9f21f7fe-d972-4c6a-b30e-1e9e60f013ac)

**Comment by Tofaa2** [comment]
> and why im need pass location here ![image](https://private-user-images.githubusercontent.com/70480001/355491762-6240bed7-e492-48d4-ad25-60f54f966009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjI3NzMsIm5iZiI6MTcyMzAyMjQ3MywicGF0aCI6Ii83MDQ4MDAwMS8zNTU0OTE3NjItNjI0MGJlZDctZTQ5Mi00OGQ0LWFkMjUtNjBmNTRmOTY2MDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA5MjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTRkZjQxMWM1YTZkMjU5ZDY1YmU4YjAzNDc4NDM0ZWNmZWI3MTdjOTIxOTg2NGIxZjE2MGI4YWMxZmZjNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QCQNX5FEC7Sakpc_agQDATeT0cxBoXQmjSsLTgqeCE) if im set it here ![image](https://private-user-images.githubusercontent.com/70480001/355491877-9f21f7fe-d972-4c6a-b30e-1e9e60f013ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjI3NzMsIm5iZiI6MTcyMzAyMjQ3MywicGF0aCI6Ii83MDQ4MDAwMS8zNTU0OTE4NzctOWYyMWY3ZmUtZDk3Mi00YzZhLWIzMGUtMWU5ZTYwZjAxM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA5MjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDQ4YzhhNGQyNzc3MTU2ZTQwNmYyYWIwYTNjZTdlZDU0MGJlNTVjMGZmMDRjMmEzYzZhMmIzNDYzNjlhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJnTwSOKKtrwXcNtebVA1efVghfwWmf47hBCD0CUqlg)

WrapperEntity#setLocation is an internal modifier of the location, its meant to be used for desync tracking and other stuff, not for generic use. Use #spawn or #teleport instead.

**Comment by mani1232** [comment]
@Tofaa2 answer pls about RotateHead

**Comment by Tofaa2** [comment]
its not implemented as of now, i will add it once im available, for now you can use setLocation(with the yaw)

**Comment by mani1232** [comment]
> its not implemented as of now, i will add it once im available, for now you can use setLocation(with the yaw)

Im need it for save in file (deserialize from WrapperEntity)

WrapperEntity dont save it, it just send it

**Comment by Tofaa2** [comment]
> > its not implemented as of now, i will add it once im available, for now you can use setLocation(with the yaw)
> 
> Im need it for save in file (deserialize from WrapperEntity)
> 
> WrapperEntity dont save it, it just send it

I told you how to save it, setLocation with the correct location + yaw and pitch

**Comment by mani1232** [comment]
![image](https://github.com/user-attachments/assets/bbe483cb-7775-462e-9daa-b1624766092c)
ok

**Comment by mani1232** [comment]
![image](https://github.com/user-attachments/assets/0cde80e5-96b8-4405-9ebc-a36373c81f85)
Create spawn() ?
(method use this.location)

**Comment by Tofaa2** [comment]
> ![image](https://github.com/user-attachments/assets/0cde80e5-96b8-4405-9ebc-a36373c81f85)
> Create spawn() ?
> (method use this.location)

I already told you, setLocation shouldn't be how you spawn and use the entity, its meant to be for patching up desyncs and other stuff if the entity is offset.
