### ISSUE TITLE
can not use com.github.Tofaa2.EntityLib

### ISSUE THREAD

**Issue by RegotlyLong** [Tofaa2/EntityLib#5]
maven:
<dependency>
            <groupId>com.github.Tofaa2.EntityLib</groupId>
            <artifactId>EntityLib</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>
        If I then maven add him, all I get will be a 1kb jar file that can't call anything about the EntityLib
        Pls fix this problem
thx

**Comment by jordoncodes** [comment]
The artifactId should be spigot, not EntityLib
```
        <dependency>
            <groupId>com.github.Tofaa2.EntityLib</groupId>
            <artifactId>spigot</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>
```

**Comment by RegotlyLong** [comment]
ok

**Comment by RegotlyLong** [comment]
But when I downloaded it, it was only 13 kb.
I want the whole thing.
It's just the same method called as v1.2.5

**Comment by jordoncodes** [comment]
idk what u mean, works for me, the 2.1.0-SNAPSHOT jar for spigot is 13kb
<img width="611" alt="Screenshot 2024-02-29 at 1 08 14 pm" src="https://github.com/Tofaa2/EntityLib/assets/98439832/5704ab23-c9fb-47c9-a776-48be6322fff7">

**Comment by Tofaa2** [comment]
> But when I downloaded it, it was only 13 kb. I want the whole thing. It's just the same method called as v1.2.5

EntityLib has zero dependencies, the jar itself is tiny. Make sure to reload your gradle cache
